apiVersion: v1
kind: Pod
metadata:
  name: bad-latest-tag
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
