apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-store
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # trước ExternalSecret (wave 1) để tránh "store not ready"
spec:
  provider:
    aws:
      service: SecretsManager    
      region: ap-southeast-1     

      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials        
            namespace: external-secrets  
            key: access-key              
          secretAccessKeySecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: secret-access-key

     