
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.4
    helm:
      values: |
        # installCRDs: tự động cài các CRD cần thiết
        # ExternalSecret, ClusterSecretStore, SecretStore, ...
        # Nếu false → phải apply CRD thủ công trước
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
      - ServerSideApply=true
