# argocd/apps/gatekeeper.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5" # Chạy đầu tiên
spec:
  project: default
  source:
    chart: gatekeeper
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    targetRevision: 3.14.0 # Chọn version ổn định tương thích với cụm
    helm:
      parameters:
        - name: currentNamespace
          value: gatekeeper-system
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 